### ISSUE TITLE
Как пользоваться?)

### ISSUE THREAD

**Issue by Myks92** [floor12/yii2-editmodal#1]
Приветсвую! Подскажите как пользоваться текущим функционалом? Не написан раздел использования. Не совсем понял)

**Comment by floor12** [comment]
Вообще, конечно, надо документацию написать свежую и актуальную.
В принципе, если добавить себе в конфиг Gii указание на использование встроенных в модуль шаблонов, то можно сгенерировать CRUD в котором большая часть функционала показана и работает. Добавить в конфиг своего приложения шаблоны модуля можно так:
```php
$config['modules']['gii'] = [
        'class' => 'yii\gii\Module',
        'allowedIPs' => ['*'],
        'generators' => [
            'class' => \floor12\editmodal\generators\crud\Generator::class
        ],
    ];
```

После чего сгенерировать CRUD для своей модели использу Gii и посмотреть как он работает.

**Comment by Myks92** [comment]
> Вообще, конечно, надо документацию написать свежую и актуальную.
> В принципе, если добавить себе в конфиг Gii указание на использование встроенных в модуль шаблонов, то можно сгенерировать CRUD в котором большая часть функционала показана и работает. Добавить в конфиг своего приложения шаблоны модуля можно так:
> 
> ```
> $config['modules']['gii'] = [
>         'class' => 'yii\gii\Module',
>         'allowedIPs' => ['*'],
>         'generators' => [
>             'class' => \floor12\editmodal\generators\crud\Generator::class
>         ],
>     ];
> ```
> 
> После чего сгенерировать CRUD для своей модели использу Gii и посмотреть как он работает.

Сделал) Но выдает ошибку Can't find variable: showForm

**Comment by Myks92** [comment]
Подключил напрямую EditModalAsset и заработало. Но иконки редактирования не определяются))

**Comment by floor12** [comment]
Надо глянуть... Вообще раньше я их брал из FontAwesome, но потом стал инлайнить свг для этих целей, для этого там есть специальный класс IconHelper, который эти иконки возвращает. Тебе наверное надо dev-master версию поставить...
